### ISSUE TITLE
zhyper custom shield

### ISSUE THREAD

**Issue by hotasfck** [ExonationZhyper/Zhyper-Pwnage-Bug-Tracker#10]
its a offhand atm :) 
https://imgur.com/a/J9FfPtv

**Comment by ExonationZhyper** [comment]
Hello, can you try equipping that item on another class that can equip off-hands such as priest? Or can you only equip it as a warrior?

**Comment by ExonationZhyper** [comment]
Hello again, it's normal for some shields to show up as off-hand (for example https://www.wowhead.com/item=39716/shield-of-assimilation).

The item is set for Warrior/Paladin anyway only so there's no way for another class to equip this.

**Comment by ExonationZhyper** [comment]
Fixed.
[http://prntscr.com/neyb79](url)
