### ISSUE TITLE
shield slam

### ISSUE THREAD

**Issue by hotasfck** [ExonationZhyper/Zhyper-Pwnage-Bug-Tracker#12]
the damage seems off to me
https://imgur.com/a/trn6tme
2k noncrit on a boomie with 1200 resi and skin up - while i am running full pve / 100% arp gear

**Comment by ExonationZhyper** [comment]
Hello,

Please do a few more duels and post more combat logs of this incident.

**Comment by ExonationZhyper** [comment]
Topic closed due to inactivity.
