### ISSUE TITLE
Blinding in Stealth

### ISSUE THREAD

**Issue by DrakeZhyper** [ExonationZhyper/Zhyper-Pwnage-Bug-Tracker#15]
If a rogue is stealthed, but you see them and use Blind on them, it won't put them out of stealth/vanish. They will be blinded while still in stealth.

**Comment by ExonationZhyper** [comment]
https://cdn.discordapp.com/attachments/525437243834368011/573623224269537295/Screenshot_1.png
https://cdn.discordapp.com/attachments/525437243834368011/573623238643548171/Screenshot_2.png

Flags --> Does not break stealth.

Blind is not supposed to break stealth, as the tooltip mentions, works as intended.

**Comment by ExonationZhyper** [comment]
Issue confirmed, fix pending.
